In [13]:
import pandas as pd
import numpy as np

In [15]:
ds = pd.Series([10,20,30,40], index=['a','b','c','d'], dtype='float', name='GHS')
print(ds)

a    10.0
b    20.0
c    30.0
d    40.0
Name: GHS, dtype: float64

In [16]:
ds = pd.Series([10,20,30,40], index=('v','h','a','b'), dtype='float', name='GHS')
print(ds)

v    10.0
h    20.0
a    30.0
b    40.0
Name: GHS, dtype: float64

In [18]:
ds = pd.Series({10:20,30:40}, dtype='float', name='GHS')
print(ds)

10    20.0
30    40.0
Name: GHS, dtype: float64

In [20]:
ds = pd.Series(np.array([10,20,30,40]), index=['v','h','a','b'], dtype='float', name='GHS')
print(ds)

v    10.0
h    20.0
a    30.0
b    40.0
Name: GHS, dtype: float64

In [29]:
ds = pd.DataFrame([['A','B','C'],[10,20,30],[1,2,3]], index=['p','q','r'], columns=['a','b','c'])
print(ds)

    a   b     c
p   A   B   NaN
q  10  20  30.0
r   1   2   3.0

In [33]:
ds = pd.DataFrame((('A','B','C'),(10,20,30),(1,None,3)), index=['p','q','r'], columns=['a','b','c'])
print(ds)

    a     b   c
p   A     B   C
q  10    20  30
r   1  None   3

In [39]:
ds = pd.DataFrame({'name': ['a','b','c'],'mark':[10,20,30], 'cgpa':[10,9.8,9.7]},index=['a','b','c'])
print(ds)

  name  mark  cgpa
a    a    10  10.0
b    b    20   9.8
c    c    30   9.7

In [45]:
ds = pd.DataFrame([{'name':'Gaurav', 'mark':10},{'name':'GHS', 'mark':10}])
print(ds)

     name  mark
0  Gaurav    10
1     GHS    10

In [59]:
df = pd.read_csv('train.csv')
df.index
df.columns
df.size
df.shape
df.values
df.dtypes
df.ndim
df.T
df = df.set_index('Name')
df = df.reset_index()
df

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",887,0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,"Graham, Miss. Margaret Edith",888,1,1,female,19.0,0,0,112053,30.0000,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",889,0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,"Behr, Mr. Karl Howell",890,1,1,male,26.0,0,0,111369,30.0000,C148,C
890,"Dooley, Mr. Patrick",891,0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [71]:
df1 = pd.DataFrame({'name':['A','B','C'],'mark':[10,20,30],'CGPI':[7,8,9]},index=['G','H','S'],columns=['name','mark','CGPI'])
df1

  name  mark  CGPI
G    A    10     7
H    B    20     8
S    C    30     9

In [72]:
df1.set_index('name',drop=True)

      mark  CGPI
name
A       10     7
B       20     8
C       30     9

In [73]:
df1.reset_index()
df1

  name  mark  CGPI
G    A    10     7
H    B    20     8
S    C    30     9

In [74]:
df = pd.read_csv('train.csv')
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [80]:
type(df['Name'])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [88]:
df[['Name','Pclass']]
# type(df[['Name','Pclass']])

                                                  Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
886                              Montvila, Rev. Juozas       2
887                       Graham, Miss. Margaret Edith       1
888           Johnston, Miss. Catherine Helen "Carrie"       3
889                              Behr, Mr. Karl Howell       1
890                                Dooley, Mr. Patrick       3

[891 rows x 2 columns]

In [96]:
df.iloc[2,3]
df.iloc[2]
df.iloc[2:3,:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S

In [89]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [97]:
df.iloc[1:0]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [100]:
df = df.set_index('Name')

KeyError: "None of ['Name'] are in the columns"

In [103]:
df = df.set_index('Name')

KeyError: "None of ['Name'] are in the columns"

In [104]:
df.loc['Braund, Mr. Owen Harris']

PassengerId       1
Survived          0
Pclass            3
Sex            male
Age              22
Name: Braund, Mr. Owen Harris, dtype: object

In [105]:
df.loc['Braund, Mr. Owen Harris','PassengerId':'Age']

PassengerId       1
Survived          0
Pclass            3
Sex            male
Age              22
Name: Braund, Mr. Owen Harris, dtype: object

In [107]:
df2 = pd.DataFrame({'P':[10,20,30],'Q':[40,50,60],'R':[70,80,90]},index=['A','B','C'])
print(df2)

    P   Q   R
A  10  40  70
B  20  50  80
C  30  60  90

In [111]:
df2.loc['B','Q']

50

In [118]:
df2.loc[:,'R']

A    70
B    80
C    90
Name: R, dtype: int64

In [119]:
df2.loc['B','Q']=100
df2

    P    Q   R
A  10   40  70
B  20  100  80
C  30   60  90

In [125]:
df2['D']=[7,8,9]
df2['E']=8
df2

    P    Q   R  D  E
A  10   40  70  7  8
B  20  100  80  8  8
C  30   60  90  9  8

In [128]:
df2['D'] = df2['P'] * df2['Q']
df2

    P    Q   R     D  E
A  10   40  70   400  8
B  20  100  80  2000  8
C  30   60  90  1800  8

In [130]:
df2.loc['A':'C','P':'R'] = 7
df2

   P  Q  R     D  E
A  7  7  7   400  8
B  7  7  7  2000  8
C  7  7  7  1800  8